name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: ["ubuntu-20.04"]
    steps:
      # - uses: actions/checkout@v3

      # - name: Composer install
      #   shell: sh
      #   run: |
      #     composer install --no-dev --no-progress
      #     tar -cf ivy-website-market.tar --exclude=src/web/_market --exclude=src/web/market-cache src vendor
      # - name: Archive build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ivy-website-market.tar
      #     path: |
      #       ivy-website-market.tar
      # - name: Run test
      #   shell: sh
      #   run: |
      #     composer install --no-progress
      #     ./vendor/bin/phpunit --log-junit phpunit-junit.xml || exit 0

      # - name: Public test report
      #   uses: mikepenz/action-junit-report@v4
      #   if: success() || failure() # always run even if the previous step fails
      #   with:
      #     report_paths: "**/phpunit-junit.xml"

      # - name: Editor checker
      #   uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Install ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 20m
          script: |
            whoami
            ls -al
