name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches: 
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: ['marketplace-runner']
    steps:
        - uses: actions/checkout@v3

        - name: Composer install
          shell: sh
          run: |
            composer install --no-dev --no-progress
            tar -cf ivy-website-market.tar --exclude=src/web/_market --exclude=src/web/market-cache src vendor
        - name: Archive build artifact
          uses: actions/upload-artifact@v3
          with:
            name: ivy-website-market.tar
            path: |
              ivy-website-market.tar
        - name: Run test
          run: |
            composer install --no-progress
            ./vendor/bin/phpunit --log-phpunit-junit.xml || exit 0

        - name: Public test report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: '**/phpunit-junit.xml'
