name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches: 
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: [marketplace-runner]
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v3
        - name: Setup PHP with PECL extension
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            tools: composer:v2
        - name: Composer install
          run: |
            xml -v
