name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches: 
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: ['marketplace-runner']
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v3

        - name: Composer install
          shell: sh
          run: |
            echo mvn -v