name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: ["marketplace.axonivy.com"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: |
            gd
            zip

      - name: Composer install
        shell: sh
        run: |
          composer install --no-dev --no-progress
          tar -cf ivy-website-market.tar --exclude=src/web/_market --exclude=src/web/market-cache src vendor

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ivy-website-market.tar
          path: |
            ivy-website-market.tar

      - name: Run test
        shell: sh
        run: |
          composer install --no-progress
          ./vendor/bin/phpunit --log-junit phpunit-junit.xml || exit 0

      - name: Public test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/phpunit-junit.xml"

    
  check-editorconfig:
    needs: build
    runs-on: ["marketplace.axonivy.com"]
    steps: 
      - name: Editor checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  deploy:
    needs: check-editorconfig
    runs-on: ["marketplace.axonivy.com"]
    if: ${{github.ref_name}} == 'MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      
      - name: Untar
        shell: sh
        run: |
          mkdir build
          targetFolder="build/ivy-website-market-$(date +'%Y-%m-%d_%H-%M-%S')" ;
          targetFile=$targetFolder.tar
          mkdir $targetFolder
          tar -xf $targetFile -C $targetFolder
          rm -f $targetFile
          mkdir deployment
          ln -fns /deployment $targetFolder/src/web
          
          cd deployment


          
        
