name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

env:
  DIST_FILE: ivy-website-market.tar

jobs:
  build:
    runs-on: ["marketplace.axonivy.com"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: |
            gd
            zip

      - name: Composer install
        shell: sh
        run: |
          composer install --no-dev --no-progress
          tar -cf ${{ env.DIST_FILE }} --exclude=src/web/_market --exclude=src/web/market-cache src vendor

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIST_FILE }}
          path: |
            ${{ env.DIST_FILE }}

      - name: Run test
        shell: sh
        run: |
          composer install --no-progress
          ./vendor/bin/phpunit --log-junit phpunit-junit.xml || exit 0

      - name: Public test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/phpunit-junit.xml"

  check-editorconfig:
    needs: build
    runs-on: ["marketplace.axonivy.com"]
    steps:
      - name: Editor checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      # - run: editorconfig-checker

  deploy:
    needs: check-editorconfig
    runs-on: ["marketplace.axonivy.com"]
    if: ${{github.ref_name}} == 'MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github'
    steps:
      - name: Deploy
        shell: sh
        run: |
          ln -fns /home/axonivya/data/market src/web/_market
          ln -fns /home/axonivya/data/market-cache src/web/market-cache
          ln -fns src/web /home/axonivya/www/market.axonivy-dev.com