name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches: 
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v3

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
        - name: Composer install
          shell: sh
          run: |
            composer install --no-dev --no-progress
            tar -cf ivy-website-market.tar --exclude=src/web/_market --exclude=src/web/market-cache src vendor
            composer install --no-progress
            ./vendor/bin/phpunit --log-juni phpunit-junit.xml || exit 0
            junit 'phpunit-junit.xml'