name: Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches: 
      - MARP-59-Migrate-the-Marketplace-from-Ivyteam-Jenkins-to-Github

jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v3

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
        - name: Composer install
          run: |
            php -v
